# Generated by Django 5.0.6 on 2024-07-15 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optirh_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llm_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.TextField()),
                ('vulgarization', models.TextField()),
                ('term_explanation', models.TextField()),
                ('trans_original', models.TextField()),
                ('trans_simplified', models.TextField()),
                ('fk_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_llm_requests_account_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
